#!/usr/bin/env bash
# ========================================================
# Script      : menu-backup
# Script by   : Mousevpn
# ========================================================

# === WARNA ===
RED='\e[31m'
GREEN='\e[32m'
WHITE='\e[97m'
NC='\e[0m' 

menu-backup-display() {
    clear
    echo -e "${WHITE}────────────────────────────${NC}"
    echo -e "${GREEN}  MENU DATABASE & BACKUP  ${NC}"
    echo -e "${WHITE}────────────────────────────${NC}"
    echo -e "1. Backup Data ke Google Drive (Manual)"
    echo -e "2. Restore Data dari Google Drive"
    echo -e "3. Ganti Akun Google Drive (Rclone)"
    echo -e "${WHITE}────────────────────────────${NC}"
    echo -e "0. Kembali ke Menu Utama"
    echo -e "${WHITE}────────────────────────────${NC}"
    
    read -p "Input Options: " opt_backup
    
    case $opt_backup in
        # Memanggil script global 'backup' yang sudah ada
        1) backup ; backup ;;       
        2) restore ; restore ;;
        3) ganti-drive ; menu-backup ;;
        0) menu ;;                       
        *) echo -e "${RED}Pilihan tidak valid!${NC}"; sleep 1; menu-backup ;;
    esac
}

menu-backup-display
